POST https://api.mezoo.me/predict
Content-Type: application/json

{
  "titles": [
    "지금이 기회! 이제 주워야할때",
    "ㅋㅋㅋㅋㅋ웃음밖에 안나온다",
    "속쓸 하한가 풀렸습니다",
    "bitx 왜 몇시간째 멈춰있는거죠?",
    "하락장에서는 QQQ ? QLD ?(TQQQ제외)",
    "채권올인러 빨간불 첨보네요.",
    "3천만원",
    "주린이) rsi는 이 둘 중 뭘 봐야되나요?? 둘다 아닌가요..??",
    "ㅋ 감히 날건드려?",
    "레버 3배 잠궜네요 ㅋㅋ",
    "무서워서 뱃살 떨립니다..",
    "본장 가서 더 빠질려나 ㅠㅠ",
    "하한가~ 하한가 신나는노래",
    "폭락장 걱정 안 하셔도 됩니다.",
    "이쯤해서 부동산쪽도 궁금합니다.",
    "마3  마5 하락한게 맞나요",
    "SOXL 8불 또 가나요",
    "남은현금으로",
    "어후 soxx 마12 이던데 서킷 걸린 soxl ㅠㅠ",
    "다들 ㅈ되셨네요 ",
    "현금비중 70프로에서 58프로",
    "토스무섭네요",
    "방향성질문",
    "웃음이나온다",
    "22년도 하락 경험있으신 분들께...",
    "사자는 소국의 경쟁에 참여 하지 않는다.",
    "데이장에서 산 sqqq 근황",
    "속슬 단 이틀동안 50퍼 빠졌네요",
    "토스앱처럼 pc로 주식 정보 볼 수 있는 곳 있을까요?",
    "증시가 빠그라질땐 항상 돈을 풀었었는데...",
    "아 저도 이대로 가는 중이네요",
    "주식/채권 비중이 50/50에서 46/54까지 벌어져서 46.5/53.5로 0.5% 리밸런싱 했네요.",
    "나스닥 월봉으로 보는 지지선",
    "쫄보는 오늘 SOXL 입성 후 바로 손절했습니다... 다들 성투하세요 .",
    "저는 환율이 더 무서운데요....",
    "엔비 본주 평단 얼마에 갖고계시나요",
    "인간지표 입니다..",
    "이거는 뭐가 있는 것 같아요…….. ",
    "8월에 FOMC 없는데 긴급 금리인하 한다면 그것도 악재인거죠?",
    "파월아 잘때가아니다 긴급회의소집한다해라  +2,로마무리하게",
    "미장x) 삼성전자 던지고 싶은데요",
    "비트코인도 앞자리 6짜로 바뀌었네요 ;;",
    "각종 예측과 오지랖이 난무한가운데 혹시",
    "인증 나오고 주식천재 빙의해서 버블 더 남았다고 즐기라는 둥 할때 눈치못챈게 흑우였네요",
    "(8.5 개인기록용) 오늘 좀 담았습니다. ",
    "두시간뒤 비행",
    "레전두 ㅋㅋㅋㅋㅋ",
    "8월 1일 100만원이 오늘 22억원.",
    "여유자금 투자) 엔비디아 vs 비트코인",
    "아직입니다.",
    "여러분들이 말도 안되는 소리 하지말라고 조롱한 SOXL 차트 입니다",
    "isa 계좌 인기라서 저도 해봤는데",
    "몇번더하락? 악재가많다? 아니다 상승한번한다",
    "와....엄청떨구네요...신규진입하시는분들은 기회인듯요",
    "엔비디아 매물대(지지선) 바로 위까지는 왔네요.",
    "예수금 빵빵한 분들은 이번 하락장에 뭘 담을 계획이세요?",
    "전 세계에서 빠진 돈 미국으로 밀집",
    "오늘은  운동빡세게하고 장 봐야겠어요",
    "시드 7.5천, +2천에서 방금 본전까지 찍힘 ",
    "soxl 매물 뭔가용",
    "국장 원래 변동성",
    "공포 그 잡채 .. 나스닥 -10퍼",
    "환율 고점일떄 사고 다른주식 고점일떄 샀더니",
    "일본이 대단하네",
    "찐고수분들 이럴때 이거담는다 추천 ㄱㄱ",
    "오른쪽 안주머니에 품었던 사직서 찢었습니다.",
    "주식 4년차... 오늘은 역대급 어려운 날이네요",
    "미니나스닥 기준 반등자리",
    "인사드립니다",
    "NVDQ 괴리율? 멈춤?",
    "올해 얼마나 날렸는지 보려면 수익률현황인가요?",
    "SOXL 살때 헷지 하세요",
    "SOXS 상한가로 거래 정지",
    "빅스가 빠질 때",
    "인플레 5.4일때는 일시적이라 아가리털더만 2프로때 되니깐 높다고 아가리터네 ㅋㅋ",
    "데이장은 거래량 없지 않음?",
    "데이장 애플이랑 테슬라 얼마인가요?",
    "않히 팔란티어 뭐죠?",
    "conl은 거래 멈췄나보네요 ㄷㄷ",
    "8월은 tmf라고 말씀 계속 드렸습니다",
    "VIX35는? 보기 드문 일 아녜요?뭔일인가요?",
    "코스닥은 외국인 기관이 줍줍 하고 있군요",
    "이 와중에 환율 오르는 중 ㅋ",
    "빅스빠지네요 다들 고생하셨습니다",
    "엔화 800대 매수한 사람들이 진정한 위너",
    "데이장 이거 뭐에요?ㅋㅋ",
    "진짜 TMF",
    "권투 체급 따지자나요",
    "무서운 베어  ",
    "[투표]현금 투입시점",
    "다음부터 안 그러시면 됩니다...",
    "SOXL, SOXS 호가창",
    "삼프장은,,,패닉셀인가요,,,",
    "침체우려 빔 개 아프네 8월5일 침체 우려의 날 기억하자",
    "qld 평단 96에사서 지금 -20% 넘으려하는데 물타기하고 기다리면 오를까요. ",
    "한국은 부동산이 답인듯",
    "키움 미주 거래 중지",
    "오늘 잘한점 잘못한점..",
    "엔비디아 무슨 단기간에 이렇게..",
    "엔화 963원"
  ]
}